### ISSUE TITLE
Cannot read property 'parentNode' of null at Avatar._scaleTextNode

### ISSUE THREAD

**Issue by dennis-8** [ambassify/react-avatar#164]
Hi,

When I create a new contact in my app there is this error: 

![image](https://user-images.githubusercontent.com/4423231/55968292-67e4d800-5c84-11e9-96c3-132783742782.png)

It's null: 
![image](https://user-images.githubusercontent.com/4423231/55968320-74693080-5c84-11e9-999d-5956863b4642.png)

**Comment by JorgenEvens** [comment]
I can make the check that should prevent this more strict. But even with the current check this should not be happening.

Could you create a small example / demo of how you are using the `Avatar` component on [codesandbox](http://codesandbox.io)? That should help me diagnose the root cause of this issue.

**Comment by gswebspace** [comment]
Experiencing similar issue.

![image](https://user-images.githubusercontent.com/13507015/61615638-2355d900-ac84-11e9-8935-6d5ffe96cb60.png)

Props passed -
```
<Avatar name={fullName} round unstyled maxInitials={2} size={35} />
```

Scope when Conditional Breakpoint was triggered -
![image](https://user-images.githubusercontent.com/13507015/61615905-c60e5780-ac84-11e9-98f1-58c381438edd.png)

Please check this issue and provide any suitable fix/suggestion, Thanks !

**Comment by JorgenEvens** [comment]
Hi @gswebspace 

Thanks for letting us know this issue still exists, however I was unable to reproduce the issue you are experiencing with the information provided ([see test](https://codesandbox.io/s/react-avatar-164-w1rqy)). Would you mind setting up a sample on [codesandbox.io](https://codesandbox.io) (or something similar) that exhibits the described behaviour? This would help a great deal in solving this issue.

**Comment by gswebspace** [comment]
Hi @JorgenEvens, I tried a very [basic integration](https://codesandbox.io/embed/boring-black-39bfd) and it works fine. So this is probably not a major issue.

My hunch is that, I am using bootstrap to show/hide user detail panels based on clicking a users avatar. That causes the available space for the list itself to change as the panel mounts and this might be triggering a media query for a few milli-seconds in which the list itself is hidden and re-appears with list+panel both(for a user nothing changes in the list area, but I can see a flicker if I really focus).

In this small gap when the timeout triggers, maybe the spanNode/parentNode actually does not exist in the dom (bcoz the whole list dissapears and comes back).
This is just a theory, you can probably understand better the code internals.

I will try to improve the css first (which can take a while), maybe that is what needs to be fixed.

**Comment by JorgenEvens** [comment]
Thanks for the update @gswebspace, I've tested for scenario's such as the one you are describing before and they didn't seem to present any issues. I'll see later today if I can re-create the issue some other way.

**Comment by jaemil** [comment]
Still have the problem with 'parentNode' of null at Avatar._scaleTextNode
It seems that react-avatar cannot handle display: none when the name is taken from an API.

Got it working with: 
`{api.username ? <Avatar
        name={api.username }
style={{display: "none"}}
      /> : null}`

**Comment by IrakliJani** [comment]
@jaemil I have the same issue.

to reproduce:
```jsx
<div style={{display: 'none'}}>
  <Avatar name={name} />
</div>
```

**Comment by IrakliJani** [comment]
@JorgenEvens @jaemil found and fixed the issue. more details in the PR https://github.com/Sitebase/react-avatar/pull/229
