### ISSUE TITLE
Remove default font-family helvetica and option to remove title

### ISSUE THREAD

**Issue by Bavaresco** [ambassify/react-avatar#220]
Remove default font-family helvetica and option to remove title.

**Comment by JorgenEvens** [comment]
Hi @Bavaresco,

The `font-family` can be overwritten to whatever you'd like it to be using the `style` property of the `Avatar` component.

Removing the `title` attribute is something I'm currently looking into: https://github.com/Sitebase/react-avatar/pull/216

**Comment by JorgenEvens** [comment]
Hi @Bavaresco,

This is now possible in the [5.0.0](https://github.com/ambassify/react-avatar/releases/tag/v5.0.0) release of react-avatar by setting the `title` property to `false` or `null`.
