### ISSUE TITLE
Breaks with AWS Amplify Console

### ISSUE THREAD

**Issue by mikhael28** [ambassify/react-avatar#223]
I don't really know why, but my Create-React-App build breaks on AWS Amplify Console (a continuous integration environment) with this library. I'm sorry, I don't have the time to write a more detailed ticket, but just thought I would post this here. Removing the package fixed the issue, and my build worked and deployed.

**Comment by Sitebase** [comment]
@mikhael28 Did you solve this eventually?

**Comment by mikhael28** [comment]
Nah I ditched it entirely - just made a custom ui component myself. I wanted to take the first letter of the first and last name for the avatar. Took like 20 minutes. Just make an array of hex-code colors that you want, then parse the first letter from the first and last name using something like this pseudocode `fName[0].toUpperCase()` and lName. Create a round border around the text (p, h2, doesn't matter) with the background color being randomly picked from the array of hex codes. Bam, you are good.

**Comment by Sitebase** [comment]
Awesome, glad you found a solution that works for you.
I'll close this issue then.
