### ISSUE TITLE
 Error: Cannot find module 'core-js-pure/stable/weak-map/index.js' in Next.js SSR

### ISSUE THREAD

**Issue by Dema** [ambassify/react-avatar#233]
we need to add `core-js-pure` to dependencies

**Comment by GertSallaerts** [comment]
We've added `core-js-pure` to peerDependencies to optimize re-use and deduplication of the dependency when `react-avatar` is installed. Modern versions of npm will resolve peerDependencies automatically but if you're on an older version you need to install it manually in your project.

**Comment by Dema** [comment]
Yeah.. I'm using yarn and right after I created an issue, I realized, that you've already added it to peerDeps! Thanks!!!
