### ISSUE TITLE
npm run build:demo

### ISSUE THREAD

**Issue by blackpintz** [ambassify/react-avatar#237]
Hi,

I forked the repo to make a few changes. But I am not able to run `npm run build:demo`. It throws this error: `error Command failed with exit code 3221225477`.
Is there a way I could fix this? Or can I run it a different way?

Thank you.

**Comment by JorgenEvens** [comment]
Hi @blackpintz,

It looks like there was an issue with webpack, I've upgraded webpack on master and the issue should be resolved.

Let me know if this has resolved the issue for you.

**Comment by blackpintz** [comment]
Hi @JorgenEvens. The issue is resolved. Thank you.
